-- Auto generated by Worm at 4/17/2014 11:54:55 AM

DROP TABLE IF EXISTS `persons`;

CREATE TABLE `persons` (
	`Id` int AUTO_INCREMENT,
	`Name` varchar(255),
	`age_in_years` int,
	`Role` text,
	`InternalState` decimal
	, PRIMARY KEY (`Id`)
) ENGINE=InnoDb DEFAULT CHARSET=utf8;

