using System;
using Worm.CodeGeneration;
using System.Collections.Generic;
using Worm.MySql.CodeGeneration.SchemaWriting;
using System.Text;

namespace Worm.MySql.CodeGeneration
{
	public class MySqlSchema : ISchema
	{
		private readonly List<Table> tables = new List<Table>();

		public MySqlSchema()
		{
			this.Name = "mysql";
			this.FileExtension = "sql";
		}

		#region ISchema: AddEntity
		public void AddEntity(PocoEntity entity)
		{
			Table t = new Table();
			t.PopulateFromPocoEntity(entity);

			this.tables.Add(t);
		}
		#endregion

		#region ISchema: Render
		public string Render()
		{
			StringBuilder sb = new StringBuilder();

			sb.AppendFormat("-- Auto generated by Worm at {0}", DateTime.Now);
			sb.AppendLine();
			sb.AppendLine();

			foreach (Table t in this.tables)
			{
				sb.AppendLine(t.GenerateScript());
			}

			return sb.ToString();
		}
		#endregion

		#region ISchema: Name
		public string Name { get; set; }
		#endregion

		#region ISchema: FileExtension
		public string FileExtension { get; set; }
		#endregion
	}
}
