using System;

namespace Worm.CodeGeneration.Internals
{
	public class Method
	{
		public Method()
		{
			this.IsAutoGenerated = false;
		}

		public string Signature { get; set; }
		public string Body { get; set; }
		public bool IsAutoGenerated { get; set; }
		public string Name { get; set; }
	}
}