// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Worm.CodeGeneration.Templates {
    using Worm.CodeGeneration.Internals;
    using System;
    
    
    public partial class WormDbClassTemplate : WormDbClassTemplateBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 3 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
 var idField = Model.Fields.GetPrimaryKeyField(); 
            
            #line default
            #line hidden
            
            #line 4 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("using System;\nusing Worm;\nusing System.Collections.Generic;\n\nnamespace ");
            
            #line default
            #line hidden
            
            #line 8 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.WormNamespace ));
            
            #line default
            #line hidden
            
            #line 8 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\n{\n\tpublic class ");
            
            #line default
            #line hidden
            
            #line 10 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.WormClassName ));
            
            #line default
            #line hidden
            
            #line 10 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(" : ");
            
            #line default
            #line hidden
            
            #line 10 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.PocoClassName ));
            
            #line default
            #line hidden
            
            #line 10 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\n\t{\n\t\t");
            
            #line default
            #line hidden
            
            #line 12 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
 foreach (PocoField f in Model.Fields.GetValueTrackedFields()) { 
            
            #line default
            #line hidden
            
            #line 13 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\n\t\t[AutoGenerated()]\n\t\tprivate bool hasChanged_");
            
            #line default
            #line hidden
            
            #line 15 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( f.Name ));
            
            #line default
            #line hidden
            
            #line 15 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(" = false;\n\t\t");
            
            #line default
            #line hidden
            
            #line 16 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 17 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\n\t\t");
            
            #line default
            #line hidden
            
            #line 18 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
 foreach (PocoField f in Model.Fields.GetValueTrackedFields()) { 
            
            #line default
            #line hidden
            
            #line 19 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\n\t\t[AutoGenerated()]\n\t\t");
            
            #line default
            #line hidden
            
            #line 21 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( f.AccessModifier.ToString().ToLower() ));
            
            #line default
            #line hidden
            
            #line 21 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(" override ");
            
            #line default
            #line hidden
            
            #line 21 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( f.Type ));
            
            #line default
            #line hidden
            
            #line 21 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 21 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( f.Name ));
            
            #line default
            #line hidden
            
            #line 21 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\n\t\t{\n\t\t\tset\n\t\t\t{\n\t\t\t\tthis.hasChanged_");
            
            #line default
            #line hidden
            
            #line 25 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( f.Name ));
            
            #line default
            #line hidden
            
            #line 25 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(" = ");
            
            #line default
            #line hidden
            
            #line 25 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( GetTrackValueComparisonForField(f) ));
            
            #line default
            #line hidden
            
            #line 25 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\n\t\t\t\tbase.");
            
            #line default
            #line hidden
            
            #line 26 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( f.Name ));
            
            #line default
            #line hidden
            
            #line 26 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(" = value;\n\t\t\t}\n\t\t}\n\n\t\t");
            
            #line default
            #line hidden
            
            #line 30 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 31 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\n\t\t");
            
            #line default
            #line hidden
            
            #line 32 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"

			if (!OutputMethodIfExists("DbIsNew"))
			{
				
            
            #line default
            #line hidden
            
            #line 36 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("[AutoGenerated()]\n\t\tprivate bool DbIsNew()\n\t\t{\n\t\t\treturn base.");
            
            #line default
            #line hidden
            
            #line 39 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( idField.Name ));
            
            #line default
            #line hidden
            
            #line 39 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(" == default(");
            
            #line default
            #line hidden
            
            #line 39 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( idField.Type ));
            
            #line default
            #line hidden
            
            #line 39 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(");\n\t\t}\n\t\t\t\t");
            
            #line default
            #line hidden
            
            #line 41 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"

			}
		
            
            #line default
            #line hidden
            
            #line 44 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\n\t\t");
            
            #line default
            #line hidden
            
            #line 45 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"

			if (!OutputMethodIfExists("DbGetByIdOrDefault"))
			{
				WriteLine("[AutoGenerated()]");
				
            
            #line default
            #line hidden
            
            #line 50 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\t\t");
            
            #line default
            #line hidden
            
            #line 50 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DbGetByIdOrDefaultTemplate.Render() ));
            
            #line default
            #line hidden
            
            #line 50 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"

				WriteLine(String.Empty);
			}
		
            
            #line default
            #line hidden
            
            #line 54 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\n\t\t");
            
            #line default
            #line hidden
            
            #line 55 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"

			if (!OutputMethodIfExists("DbSave"))
			{
				
            
            #line default
            #line hidden
            
            #line 59 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("[AutoGenerated()]\n\t\tpublic ");
            
            #line default
            #line hidden
            
            #line 60 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.PocoClassName ));
            
            #line default
            #line hidden
            
            #line 60 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(" DbSave(IWormDbConnection db)\n\t\t{\n\t\t\tif (this.DbIsNew())\n\t\t\t{\n\t\t\t\treturn this.DbInsert(db);\n\t\t\t}\n\t\t\t\n\t\t\treturn this.DbUpdate(db);\n\t\t}\n\t\t\t\t");
            
            #line default
            #line hidden
            
            #line 69 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"

			}
		
            
            #line default
            #line hidden
            
            #line 72 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\t\t\n\t\t");
            
            #line default
            #line hidden
            
            #line 73 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"

			if (!OutputMethodIfExists("DbInsert"))
			{
				WriteLine("[AutoGenerated()]");
				
            
            #line default
            #line hidden
            
            #line 78 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\t\t");
            
            #line default
            #line hidden
            
            #line 78 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DbInsertTemplate.Render() ));
            
            #line default
            #line hidden
            
            #line 78 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"

				WriteLine(String.Empty);
			}
		
            
            #line default
            #line hidden
            
            #line 82 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\n\t\t");
            
            #line default
            #line hidden
            
            #line 83 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"

			if (!OutputMethodIfExists("DbUpdate"))
			{
				WriteLine("[AutoGenerated()]");
				
            
            #line default
            #line hidden
            
            #line 88 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\t\t");
            
            #line default
            #line hidden
            
            #line 88 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DbUpdateTemplate.Render() ));
            
            #line default
            #line hidden
            
            #line 88 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"

				WriteLine(String.Empty);
			}
		
            
            #line default
            #line hidden
            
            #line 92 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\n\t\t");
            
            #line default
            #line hidden
            
            #line 93 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"

			if (!OutputMethodIfExists("Populate"))
			{
				
            
            #line default
            #line hidden
            
            #line 97 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("[AutoGenerated()]\n\t\tpublic void Populate(IWormDataReader dr)\n\t\t{\n\t\t");
            
            #line default
            #line hidden
            
            #line 100 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
 foreach (PocoField f in Model.Fields) { 
            
            #line default
            #line hidden
            
            #line 101 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\t");
            
            #line default
            #line hidden
            
            #line 101 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( GetPopulateForField(f) ));
            
            #line default
            #line hidden
            
            #line 101 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\n\t\t");
            
            #line default
            #line hidden
            
            #line 102 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 103 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 104 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
 foreach (PocoField f in Model.Fields.GetValueTrackedFields()) { 
            
            #line default
            #line hidden
            
            #line 105 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\t\t\tthis.hasChanged_");
            
            #line default
            #line hidden
            
            #line 105 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( f.Name ));
            
            #line default
            #line hidden
            
            #line 105 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write(" = false;\n");
            
            #line default
            #line hidden
            
            #line 106 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 107 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\t\t}\n\t\t\t\t");
            
            #line default
            #line hidden
            
            #line 108 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"

				WriteLine(String.Empty);
			}
		
            
            #line default
            #line hidden
            
            #line 112 "/home/pingvinen/gitclones/me/worm/src/wormlib/CodeGeneration/Templates/WormDbClassTemplate.tt"
            this.Write("\t}\n}");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        protected virtual void Initialize() {
        }
    }
    
    public class WormDbClassTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((this.formatProvider == null)) {
                        throw new global::System.ArgumentNullException("formatProvider");
                    }
                    this.formatProvider = value;
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
