#!/usr/bin/env bash

MYSQL_ROOT_PSW='123456'

apt-get update

#
# get the mariadb repository
# https://downloads.mariadb.org/mariadb/repositories/#mirror=hs-esslingen&distro=Ubuntu&distro_release=precise&version=10.0
# and install the server
#
apt-get install python-software-properties -y
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db -y
add-apt-repository 'deb http://mirror2.hs-esslingen.de/mariadb/repo/10.0/ubuntu precise main' -y
apt-get update

# http://dba.stackexchange.com/a/49880
export DEBIAN_FRONTEND=noninteractive
debconf-set-selections <<< "mariadb-server-10.0 mysql-server/root_password password $MYSQL_ROOT_PSW"
debconf-set-selections <<< "mariadb-server-10.0 mysql-server/root_password_again password $MYSQL_ROOT_PSW"
apt-get install -y --allow-unauthenticated mariadb-server

# allow network access to db
sed -i 's/bind-address/#bind-address/' /etc/mysql/my.cnf
mysql -u root -p$MYSQL_ROOT_PSW -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '$MYSQL_ROOT_PSW' WITH GRANT OPTION;"
mysql -u root -p$MYSQL_ROOT_PSW -e "flush privileges;"
service mysql stop
service mysql start

echo ""
echo ""
echo ""
echo "You can now connect to MariaDb using..."
echo "mysql -h 172.16.5.5 -u root -p$MYSQL_ROOT_PSW"
echo ""
