# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.5.3"

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/precise32"
  config.vm.provision :shell, :path => "bootstrap"
  config.vm.network "private_network", ip: "172.16.5.5"

  config.vm.hostname = "worm-fullflowdbs"

end
